import { defineConfig } from 'vitest/config';
import path from 'node:path';

export default defineConfig({
  // The graphql modules (`src/graphql/queries.js` and `subscriptions.js`) are
  // generated by `make local.config` and gitignored. Vite's import-analysis
  // resolves paths at transform time, before vi.mock() intercepts — so tests
  // that import those modules fail unless the paths physically resolve.
  // Alias them to stubs so the test runner can load them; vi.mock() then
  // replaces them at runtime with test doubles.
  resolve: {
    alias: [
      {
        find: /.*\/graphql\/queries\.js$/,
        replacement: path.resolve(__dirname, 'src/test-stubs/graphql/queries.js'),
      },
      {
        find: /.*\/graphql\/subscriptions\.js$/,
        replacement: path.resolve(__dirname, 'src/test-stubs/graphql/subscriptions.js'),
      },
    ],
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test-setup.ts'],
    exclude: ['**/node_modules/**'],
    reporters: ['default', ['junit', { outputFile: '../reports/junit-overlays.xml' }]],
  },
});
