// Test stub — real file is generated by `make local.config` into src/graphql/queries.js (gitignored).
// This stub exists so Vite's import-analysis can resolve the module path at transform time.
// vi.mock('../../graphql/queries.js', ...) replaces this at test runtime.
export const getLeaderboard = null;
