// Test stub — real file is generated by `make local.config` into src/graphql/subscriptions.js (gitignored).
// This stub exists so Vite's import-analysis can resolve the module path at transform time.
// vi.mock('../../graphql/subscriptions.js', ...) replaces this at test runtime.
export const onNewOverlayInfo = null;
export const onNewLeaderboardEntry = null;
export const onDeleteLeaderboardEntry = null;
